name: Deploy Codeberg Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: docker
    steps:
      - name: Checkout
        uses: https://code.forgejo.org/actions/checkout@v4

      - name: Setup Node.js
        uses: https://code.forgejo.org/actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build site
        run: npm run build

      - name: Deploy to Codeberg Pages
        uses: https://codeberg.org/Codeberg-CI/git-pages/action@v2
        with:
          token: ${{ forge.token }}
          source: dist/
          site: "https://${{ forge.repository_owner }}.codeberg.page/"
